---
- name: installing lamp-stack
  hosts: ansi-node1
  remote_user: root

  tasks:
    - name: Installing Apache
      yum:
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Install MYSQL DB Community edition
      dnf:
        name:
        - mysql-server
        state: latest

    - name: Start the MYSQL service
      service:
        name: mysqld
        enabled: yes
        state: started


    - name: Installing PHP
      yum:
        name:
          - php
          - php-mysqlnd
        state: latest

    - name: Copying your php file in the /var/www/html
      copy:
        src: /root/ansible/index.html
        dest: /var/www/html/index.html 
